name: "[PR] Validate Remote Configs"
on:
  pull_request:
    paths:
      - backends/remote-configs/**
      - .github/workflows/pr-deploy-remote-config.yml
env:
  BUN_VERSION: 1.2.22
  NODE_VERSION: 22.*

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./backends/remote-configs

jobs:
  lint-remote-config:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Install pre-requisites.
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun lint

  validate-remote-config:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./backends/remote-configs
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: "npm"
      #     cache-dependency-path: "**/package-lock.json"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun i --frozen-lockfile

      # Dry run remote config deployment to find template issues.
      # DEV.
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIMEX_COURSIER_DEV }}"
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: vimex-coursier-dev
      - name: Validate DEV remote config
        run: bun deploy.ts --environment=dev --dry_run

      # Dry run remote config deployment to find template issues.
      # PRE.
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIMEX_COURSIER_PRE }}"
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: vimex-coursier-pre
      - name: Validate PRE remote config
        run: bun deploy.ts --environment=pre --dry_run

      # PROD.
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIMEX_COURSIER_PROD }}"
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: vimex-coursier
      - name: Validate PROD remote config
        run: bun deploy.ts --environment=prod --dry_run
