# This workflow deploys the cloud functions to Firebase on manual dispatch.

name: "[PRE] Deploy Cloud Functions"
on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./backends/functions

env:
  BUN_VERSION: 1.2.22
  FIREBASE_PROJECT_ID: vimex-coursier-pre

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun i --frozen-lockfile

      # Download the latest firebase tools.
      - run: bun add -g firebase-tools

      # Setup credentials for Firebase and Google Cloud tools.
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIMEX_COURSIER_PRE }}"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.FIREBASE_PROJECT_ID }}

      # Create .env file.
      - run: |
          echo "PUBLIC_WEBAPP_URL=https://admin-vimex-pre.web.app" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID_PRE }}" >> .env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
          echo "GOOGLE_MAPS_API_KEY_BACKEND=${{ secrets.GOOGLE_MAPS_API_KEY_BACKEND_PRE }}" >> .env

      # Deploy Cloud Functions.
      # The double --force is not a mistake — the second one applies to artifact policy setup.
      - run: >
          firebase deploy --force --project "${{ env.FIREBASE_PROJECT_ID }}" 
          --only functions 
          -m "Deployment of cloud functions to pre environment"
          --force
