name: "[PROD] Deploy Remote Configs"
on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  BUN_VERSION: 1.2.22
  NODE_VERSION: 22.*
  WORK_FLOW_FILE_NAME: prod-deploy-remote-config

defaults:
  run:
    working-directory: ./backends/remote-configs

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # True if changes are detected or tag does not exist.
      changeDetected: ${{ steps.filter.outputs.src == 'true' || steps.tag_check.outputs.exists == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if tag exists
        id: tag_check
        run: |
          TAG_NAME="${{ env.WORK_FLOW_FILE_NAME }}"
          if git ls-remote --tags origin "refs/tags/$TAG_NAME" | grep "$TAG_NAME" > /dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - uses: dorny/paths-filter@v3
        id: filter
        if: steps.tag_check.outputs.exists == 'true'
        with:
          base: ${{ env.WORK_FLOW_FILE_NAME }}
          filters: |
            src:
              - '.github/workflows/prod-deploy-remote-config.yml'
              - 'backends/remote-configs/**'

  lint-remote-config:
    needs: changes
    if: ${{ needs.changes.outputs.changeDetected }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Install pre-requisites.
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun lint

  deploy-remote-config:
    needs: lint-remote-config
    if: ${{ needs.lint-remote-config.result == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun i --frozen-lockfile

      # Setup credentials for Firebase and Google Cloud tools.
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIMEX_COURSIER_PROD }}"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: vimex-coursier

      # Deploy Firebase Remote Config settings.
      - run: bun deploy.ts --environment=prod

  update-tag:
    needs: deploy-remote-config
    if: ${{ needs.deploy-remote-config.result == 'success' }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Update workflow base tag.
      - name: Update tag to current commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag -f "$TAG_NAME"
          git push origin -f "$TAG_NAME"
        env:
          TAG_NAME: ${{ env.WORK_FLOW_FILE_NAME }}
