# Template for public repository workflows that fetch private repository
# This template uses actions/checkout@v4 with authentication token

name: "Template - Fetch Private Repo"

on:
  workflow_dispatch:

env:
  PRIVATE_REPO_BRANCH: main

jobs:
  fetch-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4
        
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: vimex-sarl/delivery
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: private-repo
          ref: ${{ env.PRIVATE_REPO_BRANCH }}
          
      - name: Verify private repository structure
        run: |
          ls -la private-repo/
          echo "Private repository checked out successfully"
