# Template for public repository workflows that fetch private repository
# This template includes the necessary steps to clone the private repository

name: "Template - Fetch Private Repo"

on:
  workflow_dispatch:

env:
  PRIVATE_REPO_URL: git@github.com:vimex-sarl/delivery.git
  PRIVATE_REPO_BRANCH: main

jobs:
  fetch-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Setup Git for private repository access
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Clone private repository
        run: |
          # Create SSH key for private repo access
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_REPO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add GitHub to known hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Clone private repository
          git clone $PRIVATE_REPO_URL private-repo
          cd private-repo
          git checkout $PRIVATE_REPO_BRANCH

      - name: Verify private repository structure
        run: |
          ls -la private-repo/
          echo "Private repository cloned successfully"
